import tools.rtems_waf.rtems as rtems

def init(ctx):
    rtems.init(ctx, version="6", long_commands=True)

def options(opt):
    rtems.options(opt)

def configure(conf):
    rtems.configure(conf)

def build(bld):
    rtems.build(bld)
    bld(
        features='c cprogram',
        target='hello_world',
        cflags='-g -O2',
        source='src/init.c',
    )
